spring:
  application:
    name: CONFIG-DEV


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registery: true
    register-with-eureka: true
    service-url:
      defeaultZone: http://localhost:8761/eureka
